# Generated by Django 5.2 on 2025-05-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Generolibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AlmacenLibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('año', models.CharField(max_length=200)),
                ('critica_de_internet', models.CharField(max_length=200)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clasificacionlibros')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.generolibros')),
            ],
        ),
    ]
