# Generated by Django 5.2 on 2025-05-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_clasificacionlibros_generolibros_almacenlibros'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ID_usuario',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contraseña',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='correo',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
