# Generated by Django 5.2 on 2025-05-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_project_id_usuario_project_contraseña_project_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDeLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('leido', 'Leído'), ('leyendo', 'Leyendo'), ('quiero', 'Quiero Leer')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.almacenlibros')),
            ],
        ),
    ]
