# Generated by Django 5.2 on 2025-05-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_estadodelectura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadodelectura',
            name='autor',
        ),
    ]
