# Generated by Django 5.2 on 2025-05-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_estadodelectura_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseñaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_reseña', models.TextField()),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calificación del 1 al 5')),
                ('estado_lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadodelectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
            ],
        ),
    ]
