# Generated by Django 5.2 on 2025-06-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reseñalibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñalibro',
            name='estado_lectura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.almacenlibros'),
        ),
    ]
