# Generated by Django 5.2 on 2025-07-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_almacenlibros_created_almacenlibros_datecompleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenlibros',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='reseñalibro',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
    ]
