# Generated by Django 5.2 on 2025-07-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_almacenlibros_critica_de_internet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenlibros',
            name='critica_de_internet',
            field=models.CharField(max_length=200),
        ),
    ]
