# Generated by Django 5.2 on 2025-07-04 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_almacenlibros_critica_de_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenlibros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
