# Generated by Django 5.2 on 2025-07-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_almacenlibros_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenlibros',
            name='descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacenlibros',
            name='clasificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calificación del 1 al 5'),
        ),
    ]
