# Generated by Django 5.2 on 2025-07-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_almacenlibros_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenlibros',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clasificacionlibros'),
        ),
        migrations.AlterField(
            model_name='almacenlibros',
            name='critica_de_internet',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Calificación del 1 al 5'),
        ),
    ]
